# Deal & buying guides with shop links. Links are built in build.py from the
# "aff" settings in products.json (Amazon tag, Admitad deeplink bases), so the
# same pages earn commission as soon as the tags are added.
# Each guide: (slug, title, meta description, intro html, sections, tool_slug, product_slug)
# section: (heading, text, [(item name, why it saves money, search query), ...])

D = [
("black-friday-what-to-buy",
 "What to Buy on Black Friday 2026 (and What to Skip)",
 "The product categories that usually get real Black Friday discounts, what to skip, and quick links to compare prices on Amazon and AliExpress.",
 """<p>Black Friday 2026 is on <strong>Friday, November 27</strong>, with Cyber Monday on November 30. Not every "deal" is a deal, but some categories reliably get their lowest prices of the year. Use this list to plan, then set a target price for each item before the sale starts.</p>""",
 [("Usually worth buying",
   "These categories often see their biggest discounts of the year around Black Friday and Cyber Monday.",
   [("TVs", "Retailers compete hard on TVs; compare the exact model number across stores.", "4k smart tv"),
    ("Headphones and earbuds", "Popular models are frequently discounted; check the price history before buying.", "wireless earbuds"),
    ("Kitchen appliances", "Air fryers, blenders and coffee makers are classic Black Friday doorbusters.", "air fryer"),
    ("Robot vacuums", "Often discounted heavily in November.", "robot vacuum"),
    ("Power tools", "Tool sets and combo kits are a Black Friday favourite.", "cordless drill set"),
    ("Toys and games", "Buy holiday gifts early while stock is good.", "lego set")]),
  ("Usually better to wait or skip",
   "Prices for these often drop at other times of year, or Black Friday versions are cut-down models.",
   [("Winter clothing", "Coats and boots are often cheaper in January sales.", "winter coat"),
    ("Brand-new phones", "Flagships launched in September rarely drop much in November.", "phone case")]),
 ],
 "black-friday-countdown", "black-friday-deal-planner-2026"),

("money-saving-kitchen-tools",
 "Kitchen Tools That Help You Spend Less on Groceries",
 "Simple kitchen tools that cut food waste and grocery bills: storage containers, a kitchen scale, slow cookers and more, with price comparison links.",
 """<p>The fastest way to lower your grocery bill is to waste less food and buy in bulk when the unit price is right. These everyday tools make both easier. Compare prices before you buy, and work out unit prices with our free <a href="../../tools/grocery-unit-price-calculator/">grocery unit price calculator</a>.</p>""",
 [("Store food so it lasts longer",
   "Food that spoils is money in the bin.",
   [("Glass food storage containers", "Keep leftovers fresh and visible so they get eaten.", "glass food storage containers"),
    ("Vacuum sealer", "Lets you buy meat and cheese in bulk and freeze portions.", "vacuum sealer machine"),
    ("Reusable produce bags", "Help fruit and vegetables last longer in the fridge.", "reusable produce bags")]),
  ("Cook cheaper meals at home",
   "Batch cooking at home is much cheaper than takeaway.",
   [("Slow cooker", "Turns cheap cuts and beans into easy meals.", "slow cooker"),
    ("Air fryer", "Quick home meals instead of ordering in.", "air fryer"),
    ("Digital kitchen scale", "Weigh portions and compare price per gram or ounce.", "digital kitchen scale")]),
 ],
 "grocery-unit-price-calculator", "grocery-price-book-deal-finder"),

("energy-saving-gadgets",
 "Cheap Energy-Saving Gadgets That Lower Your Bills",
 "Low-cost gadgets that help reduce electricity and heating bills at home: LED bulbs, smart plugs, draught stoppers and more.",
 """<p>Small changes at home add up on every bill. These low-cost items are some of the easiest ways to use less electricity and heat. Add the savings to your budget with our free <a href="../../tools/budget-calculator-50-30-20/">50/30/20 budget calculator</a>.</p>""",
 [("Electricity",
   "Cut the power you use without changing much else.",
   [("LED light bulbs", "Use far less power than old incandescent bulbs.", "led light bulbs"),
    ("Smart plugs with energy monitoring", "Switch off devices on standby and see what they use.", "smart plug energy monitoring"),
    ("Power strip with switches", "Turn off TVs and chargers at the wall in one go.", "surge protector power strip individual switches")]),
  ("Heating and cooling",
   "Keep warm air in during winter and cool air in during summer.",
   [("Door draught stopper", "Blocks cold air under doors.", "door draft stopper"),
    ("Window insulation film", "A cheap extra layer for single-glazed windows.", "window insulation film kit"),
    ("Thermal curtains", "Help keep rooms warm in winter.", "thermal blackout curtains")]),
 ],
 "budget-calculator-50-30-20", "paycheck-budget-planner"),

("home-office-on-a-budget",
 "Home Office Setup on a Budget: What You Really Need",
 "A budget home office checklist for remote work and study: monitor, chair support, lighting and cables, with links to compare prices.",
 """<p>You don't need an expensive setup to work comfortably from home. Start with the items that make the biggest difference to comfort and focus, and add the rest later.</p>""",
 [("Comfort first",
   "Neck, back and eyes matter more than gadgets.",
   [("Laptop stand", "Raises the screen to eye level.", "laptop stand adjustable"),
    ("Lumbar support cushion", "A cheap upgrade for any chair.", "lumbar support pillow office chair"),
    ("Desk lamp", "Good light reduces eye strain.", "led desk lamp")]),
  ("Work faster",
   "Small add-ons that save time every day.",
   [("External monitor", "A second screen is a big productivity boost.", "24 inch monitor"),
    ("USB-C hub", "Connect monitor, keyboard and drives with one cable.", "usb c hub"),
    ("Wireless keyboard and mouse", "Comfortable typing with a laptop stand.", "wireless keyboard mouse combo")]),
 ],
 "budget-calculator-50-30-20", "paycheck-budget-planner"),

("christmas-gift-ideas-under-25",
 "Christmas Gift Ideas Under $25 (USA, UK & Canada)",
 "Affordable Christmas gift ideas under $25 / £20 for family, friends and coworkers, plus tips to stay on your holiday budget.",
 """<p>Set a gift budget first, then shop. A simple rule: decide a total, divide it by the number of people, and stick to it. Our free <a href="../../free-black-friday-wishlist/">Black Friday wishlist</a> keeps track of target prices and how much budget is left.</p>""",
 [("For anyone",
   "Safe, useful gifts most people like.",
   [("Cosy blanket", "Always welcome in winter.", "fleece throw blanket"),
    ("Insulated travel mug", "Useful every day.", "insulated travel mug"),
    ("Board or card game", "Fun for the whole family.", "family card game")]),
  ("For coworkers and teachers",
   "Small, thoughtful and easy to wrap.",
   [("Scented candle", "A classic small gift.", "scented candle gift set"),
    ("Notebook and pen set", "Practical for work.", "notebook gift set"),
    ("Hand cream gift set", "Popular in cold weather.", "hand cream gift set")]),
 ],
 "black-friday-countdown", "black-friday-deal-planner-2026"),
]
